Project Name:
- TheImperialGod
Language:
- Python 3.9.1
- discord.py 1.5.1
Description:
- It is an awesome discord bot with plenty of features
Commands:
- 85
Features:
- Utilities for server optimization
- Custom help command
- Reddit commands (i.e. dog, meme, cat)
- Powerful giveaway features
- Economy Features and commands
- Web Dashboard (in progress)
- Toggleable automoderation
- Tickets to contact staff
- Moderation to the next level
- Administrator commands
Owners:
- NightZan999
- CaCO3
Collaborators:
- CaCO3
Contributors:
- Makiyu-py
- Dragonizedpizza
- JakeLion
- CaCO3
